### ISSUE TITLE
Question about persistence

### ISSUE THREAD

**Issue by cenosito** [moozzyk/puppeteer-docker-RPi#2]
How could I have persistence in the container execution? 

Currently, I run the following command:

`docker run --rm puppeteer-docker`

What my index.js does is take a screenshot and perform read and write operations on a file every time I run the container. 
Is there a way for me to access that screenshot and the content of the file?

Thanks for share your work!

**Comment by moozzyk** [comment]
As per the [documentation](https://docs.docker.com/engine/reference/run/#clean-up---rm) `docker --rm` _automatically cleans up the container and remove the file system when the container exits_. If you want to be able to access files you created when running the container you either need to run your docker differently or use a named volume and store your files on this volume.
